config/routes.rb
Rails.application.routes.draw do

  resources :liens
  get 'promo/:year' => 'promo#index', as: 'promo' , :defaults => { :year => Time.now.to_s(:school_year) }


  # Module SOS
  get 'alerts/index'
  post 'alerts/create'

  #Workshops routes, cannot use ressoures because we want to know the promo year
  put 'workshops/addto/:id_workshop/:id_project'=> 'workshops#addto', as: 'add_to_project'
  put 'workshops/switchto/:id_workshop/:id_old_project/:id_project'=>'workshops#switchto', as: 'switch_to_project'
  get 'workshops/:year/:id' => 'workshops#show', as: 'workshop', :defaults => { :year => Time.now.to_s(:school_year) }
  get 'workshops/:year' => 'workshops#show', as: 'workshops', :defaults => { :year => Time.now.to_s(:school_year) }
  get 'workshops' => 'workshops#show'
  get 'workshops/edit/:year/:id'=> 'workshops#edit', as: 'edit_workshop', :defaults => { :year => Time.now.to_s(:school_year) }
  delete 'workshops/:year/:id'=> 'workshops#destroy'
  put 'workshops/:year/:id'=> 'workshops#update'
  patch 'workshops/:year/:id'=> 'workshops#update', as: 'update_workshop'



  get 'home/index'

  authenticated :user do
    root to: 'workshops#show', as: :authenticated_root
  end

  devise_for :users, :controllers => {:registrations => "users/registrations"}
  root :to => "home#index"

  resources :create_workshop
  #get '/workshop/:id/edit' => 'create_workshop#wicked_first', :as => 'edit_workshop'

  # , only: [:show, :update]
  # controller :workshops do
  #   resources :create_workshop, only: :update
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/workshop.rb
# == Schema Information
#
# Table name: workshops
#
#  id             :integer          not null, primary key
#  name           :string
#  description    :text
#  user_id        :integer
#  teacher        :string
#  begins         :date
#  ends           :date
#  teamgeneration :integer
#  teamnumber     :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Workshop < ApplicationRecord
  include FriendlyId
  friendly_id :slug_candidates, use: :slugged
  def should_generate_new_friendly_id?
    name_changed?
  end
  # Try building a slug based on the following fields in
# increasing order of specificity.
  def slug_candidates
    [
      :name,
      [:name, :year],
      [:name, Time.now]
    ]
  end

  has_many :projects, dependent: :destroy # Destroy associated projects
  belongs_to :user
  has_many :users, through: :projects


  validates :name, :description, :teacher, :begins, :ends, :teamgeneration, :projectleaders,:teamnumber, presence: true
  validates :teamnumber, numericality: { only_integer: true, :greater_than_or_equal_to => 1, :less_than_or_equal_to => User.where('year = ? AND status=0 OR status=1',Time.now.to_s(:school_year) ).count}
  validates_date :begins, :on_or_before => lambda { :ends }
  accepts_nested_attributes_for :projects

  # Method to define the params use when generating ral path
  def to_param
    {year: year, id: slug}
  end

end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :set_workshop, only: [:show, :edit, :update, :destroy]
  #before_filter :authenticate_user! # Need to be connect to access at these pages
  # GET /workshops
  # GET /workshops.json
  def index
    # @workshop = @workshops.last # Useful to display the last workshop
    # if @workshops.count != 0 # If there is no workshop, don't create these variables
    #   @id = @workshop.id
    #   @project = @workshop.projects
    #   @count = count_groups(@project)
    # end
    # render :show

  end

  # GET /workshops/1
  # GET /workshops/1.json
  def show
    if @workshops.count != 0 # If there is no workshop, don't create these variables
      @id = @workshop.id
      @projects = @workshop.projects
      if current_user.projects.find_by(workshop_id: @id)
        @current_project_id = current_user.projects.find_by(workshop_id: @id).id
      else
        @current_project_id = nil
      end

    end
  end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
  end

  # GET /workshops/1/edit
  def edit
    if session[:workshop_data]
      respond_to do |format|
          format.html { render :edit }
      end
    end


  end


  def create
    @workshop = Workshop.new(workshop_params)
    @workshop.user_id = current_user.id # Give the current user id at the new workshop

    respond_to do |format|
      if @workshop.save
        format.html { render :new, notice: I18n.t('views.workshop.flash_messages.workshop_was_successfully_created') }
        format.json { render :show, status: :created, location: @workshop }
      else
        format.html { render :new }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  def addto



    current_user.projects << Project.find(params[:id_project])
    # @params_user=User.find(current_user)
    # @params_projet=Project.find(params[:id_group])
    #
    # @params_projet.works.create(user: @params_user)

    redirect_to workshop_path(params[:id_workshop])

  end

  def switchto


    current_user.projects.delete(Project.find(params[:id_old_project]))
    current_user.projects << Project.find(params[:id_project])
    # @params_user=User.find(current_user)
    # @params_projet=Project.find(params[:id_group])
    # @work = Work.find(params[:id_group_current])
    # @work.destroy
    # @params_projet.works.create(user: @params_user)
    # work.project_id = params[:id_group]
    # work.save

    redirect_to workshop_path(params[:id_workshop])

  end


  # PATCH/PUT /workshops/1
  # PATCH/PUT /workshops/1.json
  def update
    respond_to do |format|
      if @workshop.update(workshop_params)
        format.html { redirect_to @workshop.to_param, notice: I18n.t('views.workshop.flash_messages.workshop_was_successfully_updated') }
        format.json { render :show, status: :ok, location: @workshop }
      else
        format.html { render :edit }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    if session[:workshop_unfinished] == @workshop.id
      session.delete(:workshop_unfinished)
    end
    @workshop.destroy
    respond_to do |format|
      format.html { redirect_to workshops_url, notice: I18n.t('views.workshop.flash_messages.workshop_was_successfully_deleted') }
      format.json { head :no_content }
    end
  end


  private

    # Use callbacks to share common setup or constraints between actions.
    def set_workshop
      if params[:id]
        @workshop = @workshops.friendly.find(params[:id])
      else
        @workshop = @workshops.first
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workshop_params
      params.require(:workshop).permit(:name, :description, :user_id, :teacher, :begins, :ends, :teamgeneration, :teamnumber)
    end
    def workshop_id
      params[:id]
    end
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/_form.html.erb
<%= form_for (workshop), :url => update_workshop_path(@workshop.to_param) do |f| %>
  <% if workshop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>

      <ul>
      <% workshop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-offset-2 col-md-4">

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>

  </div>

  <div class="col-md-4">

    <div class="field">
      <%= f.label :teacher %>
      <%= f.text_field :teacher %>
    </div>

    <div class="field">
      <%= f.label :begins %>
      <%= f.text_field :begins, class: "datepicker_begin" %>
    </div>

    <div class="field">
      <%= f.label :ends %>
      <%= f.text_field :ends, class: "datepicker_end" %>
    </div>

  </div>


  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <div class="actions">
        <%= f.submit "Modifier", class: "button_link" %>
        <%= link_to I18n.t('views.back'), workshops_path, class: "button_link" %>
      </div>
    </div>
  </div>
<% end %>

app/views/workshops/edit.html.erb
<section class="container-fluid bg_full_width">
  <div class="filter">
  </div>
</section>

<div class="container-fluid full_width inscription">
  <div class="content">

    <div class="design_form row">
      <div class="col-md-offset-3 col-md-6">
        <h1><%= t 'views.workshop.edit.title' %></h1>
      </div>

      <%= render 'form', workshop: @workshop %>

    </div>

  </div>
</div>

app/views/workshops/new.html.erb
<h1>New Workshop</h1>

<%= render 'form', workshop: @workshop %>

<%= link_to 'Back', workshops_path %>

app/views/workshops/show.html.erb
<p id="notice"><%= notice %></p>
<section class="container-fluid bg_full_width_workshop">
</section>

<% i = 0 %>
<% @projects.each do |project| %>
  <div class="modal fade" id="project_<%= i %>" role="dialog">
    <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h2 class="modal-title">Informations</h2>
      </div>
      <div class="modal-body">
        <h4>Description du projet </h4>
          <p><%= project.description %></p>
        <h4>Assisteront à la soutenance </h4>
        <ul>
        <% project.attendees.each do |user| %>
            <li><%= user.firstname %> <%= user.lastname %></li>
        <% end%>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>
  <% i += 1 %>
<% end %>

<div class="canvas">
  <%= link_to 'Créer un Workshop', {controller: "create_workshop"}, class: "create_workshop" %>
  <h4><i class="fa fa-list" aria-hidden="true"></i> Workshops</h4>

  <% @workshops.each do |workshop| %>
    <div class="each_workshop <% if @workshop.name == workshop.name  %> active <% end %>">

      <%= link_to workshop.name, workshop_path(workshop.to_param) %>
      <% if workshop.projects.count == 0 %>
        <i title="Processus de création non terminé !" class="fa fa-exclamation-circle project_in_creation" aria-hidden="true" style="color:#bf3939; font-size:1.5em;"></i>
      <% end %>
    </div>
  <% end %>
</div>
<div class="container-fluid full_width last_workshop_view">
  <div class="content">
    <% if Workshop.count != 0 %>

      <div class="row">
        <div class="col-md-12 title_workshop">
          <div class="filter">
            <h1><%= @workshop.name %></h1>
          </div>
        </div>
      </div>

      <div class="row wrapper_informations">
        <div class="actions_workshop">
          <%= link_to (content_tag(:i, nil, class: 'fa fa-pencil-square-o')), edit_workshop_path(@workshop.to_param) %>
          <%= link_to (content_tag(:i, nil, class: 'fa fa-trash-o')),  workshop_path(@workshop.to_param), method: :delete, data: { confirm: I18n.t('views.are_you_sure') } %>
        </div>

        <div class="col-md-5 col-sm-12">
          <div class="line_title">
            <h3><i class="fa fa-info" aria-hidden="true"></i> Informations</h3>
          </div>

          <div class="informations">
            <ul>
              <li><span class="attribut">Créé par :</span> <%= @workshop.user.firstname %></li>
              <li><span class="attribut">Professeur(s) associé(s) :</span> <%= @workshop.teacher %></li>
              <li><span class="attribut">Date de début :</span> <span class="beginDate"><%= @workshop.begins %></span></li>
              <li><span class="attribut">Date de fin :</span> <span class="endDate"><%= @workshop.ends %></span></li>
            </ul>
          </div>

          <div class="line_title">
            <h3><i class="fa fa-comment" aria-hidden="true"></i> Description</h3>
          </div>

          <div class="description">
            <p><%= @workshop.description %></p>
          </div>
        </div>

        <div class="col-md-7 col-sm-12">
          <div class="line_title">
            <h3><i class="fa fa-users" aria-hidden="true"></i> Les projets</h3>
          </div><!-- If there is no workshop, don't print on the screen -->
          <div class="every_projects">
            <!-- if user doesn't have selected a group display button 'S ajouter' for join a group -->
            <% userInWorkshop = @workshop.users.include? current_user %>
            <!-- if user have select a group display button 'Switch' for switch group -->
            <% i = 0 %>
            <% @projects.each do |project| %>

            <% userInProject = project.users.include? current_user %>

              <div class="group">
                  <p><%= project.name %><span class="pull-right">
                  <i data-toggle="modal" data-target="#project_<%= i %>" class="see_infos fa fa-info-circle" aria-hidden="true"></i></span></p>
                  <% project.users.order('works.project_leader DESC').each do |user| %>
                    <ul>
                      <li>
                        <%= user.firstname %>
                        <%= user.lastname %>
                        <% if user.works.find_by(project_id: project.id).project_leader  == 1 && @workshop.projectleaders == 1 %>
                          <i class="fa fa-star" aria-hidden="true"></i>
                        <% end %>
                      </li>
                    </ul>
                  <% end %>
                  <% if(@workshop.teamgeneration==1) %>
                    <% if !userInWorkshop  %>
                      <li class="button_link"><%= link_to "S\'ajouter", add_to_project_path(@id, project.id), method: :put%></li>
                    <% elsif !userInProject %>
                        <li class="button_link"><%= link_to "Changer",switch_to_project_path(@id,@current_project_id, project.id), method: :put%></li>
                    <% end %>
                  <% end %>
              </div>
              <% i += 1 %>
            <% end %>
            <img class="tete_logo" src="/assets/tete_logo.png" alt="Logo" />
          </div>
        </div>
      </div>

      <div class='col-md-offset-2 col-md-8' id="pbar_outerdiv">
        <div id="pbar_text"></div>
        <div id="pbar_innertext"></div>
      </div>

    <% else %>
      <div class="row">
        <div class="col-md-12 no_project">
          <%= link_to (content_tag(:i, nil, class: 'fa fa-plus-square-o')), controller: "create_workshop" %><br />
          Aucun projet :(
        </div>
      </div>
    <% end %> <!-- end if -->
  </div>
</div>

<script type="text/javascript">

</script>