config/routes.rb
Rails.application.routes.draw do

  resources :liens
  get 'promo/:year' => 'promo#index', as: 'promo' , :defaults => { :year => Time.now.to_s(:school_year) }


  # Module SOS
  get 'alerts/index'
  post 'alerts/create'

  #Workshops routes, cannot use ressoures because we want to know the promo year
  put 'workshops/addto/:id_workshop/:id_project'=> 'workshops#addto', as: 'add_to_project'
  put 'workshops/switchto/:id_workshop/:id_old_project/:id_project'=>'workshops#switchto', as: 'switch_to_project'
  get 'workshops/:year/:id' => 'workshops#show', as: 'workshop', :defaults => { :year => Time.now.to_s(:school_year) }
  get 'workshops/:year' => 'workshops#show', as: 'workshops', :defaults => { :year => Time.now.to_s(:school_year) }
  get 'workshops' => 'workshops#show'
  get 'workshops/edit/:year/:id'=> 'workshops#edit', as: 'edit_workshop', :defaults => { :year => Time.now.to_s(:school_year) }
  delete 'workshops/:year/:id'=> 'workshops#destroy'
  put 'workshops/:year/:id'=> 'workshops#update'
  patch 'workshops/:year/:id'=> 'workshops#update', as: 'update_workshop'



  get 'home/index'

  authenticated :user do
    root to: 'workshops#show', as: :authenticated_root
  end

  devise_for :users, :controllers => {:registrations => "users/registrations"}
  root :to => "home#index"

  resources :create_workshop
  #get '/workshop/:id/edit' => 'create_workshop#wicked_first', :as => 'edit_workshop'

  # , only: [:show, :update]
  # controller :workshops do
  #   resources :create_workshop, only: :update
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/lien.rb
class Lien < ApplicationRecord
end

app/controllers/liens_controller.rb
class LiensController < ApplicationController
  before_action :set_lien, only: [:show, :edit, :update, :destroy]

  # GET /liens
  # GET /liens.json
  def index
    time = Time.now
    year = time.to_s(:school_year)
    @liens = Lien.where('year = ? ', year)
  end

  # GET /liens/1
  # GET /liens/1.json
  def show
  end

  # GET /liens/new
  def new
    @lien = Lien.new
  end

  # GET /liens/1/edit
  def edit
  end

  # POST /liens
  # POST /liens.json
  def create
    @lien = Lien.new(lien_params)
    time = Time.now
    year = time.to_s(:school_year)
    @lien.year = year

    if /facebook/ =~ lien_params[:url]
      @lien.logo='facebook.png'
    elsif /twitter/ =~ lien_params[:url]
      @lien.logo='twitter.png'
    elsif /github/ =~ lien_params[:url]
      @lien.logo='github.png'
    elsif /gitter/ =~ lien_params[:url]
      @lien.logo='gitter.png'
    elsif /ppulse/ =~ lien_params[:url]
      @lien.logo='ppulse.png'
    elsif /slack/ =~ lien_params[:url]
      @lien.logo='slack.png'
    elsif /docs.google/ =~ lien_params[:url]
      @lien.logo='doc.png'
    elsif /drive.google/ =~ lien_params[:url]
      @lien.logo='googledrive.png'
    elsif /framapad/ =~ lien_params[:url]
      @lien.logo='framapad.png'
    end

    respond_to do |format|
      if @lien.save
        format.html { redirect_to liens_path, notice: 'Le lien a été ajouté avec succès.' }
        format.json { render :index, status: :created, location: @lien }
      else
        format.html { render :new }
        format.json { render json: @lien.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /liens/1
  # PATCH/PUT /liens/1.json
  def update
    respond_to do |format|
      if @lien.update(lien_params)
        format.html { redirect_to @lien, notice: 'Le lien a été mis à jour.' }
        format.json { render :index, status: :ok, location: @lien }
      else
        format.html { render :edit }
        format.json { render json: @lien.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /liens/1
  # DELETE /liens/1.json
  def destroy
    @lien.destroy
    respond_to do |format|
      format.html { redirect_to liens_url, notice: 'Le lien a été supprimé avec succès.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lien
      @lien = Lien.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lien_params
      params.require(:lien).permit(:name, :url)
    end
end

app/helpers/liens_helper.rb
module LiensHelper
end

app/views/liens/_form.html.erb
<%= form_for(lien) do |f| %>
  <% if lien.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lien.errors.count, "error") %> prohibited this lien from being saved:</h2>

      <ul>
      <% lien.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <div class="actions">
        <% if params[:action] == "new" %>
          <%= f.submit "Créer", class: "button_link" %>
        <% else %>
          <%= f.submit "Modifier", class: "button_link" %>
        <% end %>
        <%= link_to "Retour", liens_path, class: "button_link" %>
      </div>
    </div>
  </div>
<% end %>

app/views/liens/edit.html.erb
<section class="container-fluid bg_full_width">
  <div class="filter">
  </div>
</section>

<div class="container-fluid full_width inscription">
  <div class="content">
    <div class="design_form row">

      <div class="col-md-offset-3 col-md-6">

        <h1>Modifier un lien</h1>

        <%= render 'form', lien: @lien %>

      </div>
    </div>
  </div>
</div>

app/views/liens/index.html.erb
<p id="notice"><%= notice %></p>

<section class="container-fluid bg_full_width_workshop">
</section>


<div class="container-fluid full_width inscription">
  <div class="content">

    <div class="row wrapper_informations">

      <div class="col-md-7 col-sm-12">
        <div class="line_title">
          <h3><i class="fa fa-info" aria-hidden="true"></i> Liens utiles</h3>
        </div>

        <div class="informations list_link">
          <ul>
            <li class="pBottom10"><%= link_to 'Nouveau lien', new_lien_path, class: "button_link" %></li>
            <% @liens.each do |lien| %>
            <div>
              <li class="pBottom10">
                <% if lien.logo != nil %>
                  <%= image_tag lien.logo, width: 40, height: 40, alt: lien.name %>
                <% end %>
                <%= link_to lien.name, lien.url, class: "each_link" %>
                <div class="pull-right">
                  <%= link_to 'Modifier', edit_lien_path(lien), class: "button_link" %>
                  <%= link_to 'Supprimer', lien, method: :delete, data: { confirm: 'Êtes-vous sûr ?' }, class: "button_link" %>
                </div>
              </li>
            </div>

            <% end %>
          </ul>
        </div>
      </div>

      <div class="col-md-5 img_link">
        <img src="/assets/tete_logo.png" alt="Tête du cochon" />
      </div>
    </div>
  </div>
</div>

app/views/liens/new.html.erb
<section class="container-fluid bg_full_width">
  <div class="filter">
  </div>
</section>

<div class="container-fluid full_width inscription">
  <div class="content">
    <div class="design_form row">

      <div class="col-md-offset-3 col-md-6">

        <h1>Nouveau lien</h1>

        <%= render 'form', lien: @lien %>

      </div>
    </div>
  </div>
</div>

app/views/liens/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Nom:</strong>
  <%= @lien.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @lien.url %>
</p>

<%= link_to 'Modifier', edit_lien_path(@lien) %> |
<%= link_to 'Retour', liens_path %>