config/routes.rb
Rails.application.routes.draw do

  resources :liens
  get 'promo/:year' => 'promo#index', as: 'promo' , :defaults => { :year => Time.now.to_s(:school_year) }


  # Module SOS
  get 'alerts/index'
  post 'alerts/create'

  #Workshops routes, cannot use ressoures because we want to know the promo year
  put 'workshops/addto/:id_workshop/:id_project'=> 'workshops#addto', as: 'add_to_project'
  put 'workshops/switchto/:id_workshop/:id_old_project/:id_project'=>'workshops#switchto', as: 'switch_to_project'
  get 'workshops/:year/:id' => 'workshops#show', as: 'workshop', :defaults => { :year => Time.now.to_s(:school_year) }
  get 'workshops/:year' => 'workshops#show', as: 'workshops', :defaults => { :year => Time.now.to_s(:school_year) }
  get 'workshops' => 'workshops#show'
  get 'workshops/edit/:year/:id'=> 'workshops#edit', as: 'edit_workshop', :defaults => { :year => Time.now.to_s(:school_year) }
  delete 'workshops/:year/:id'=> 'workshops#destroy'
  put 'workshops/:year/:id'=> 'workshops#update'
  patch 'workshops/:year/:id'=> 'workshops#update', as: 'update_workshop'



  get 'home/index'

  authenticated :user do
    root to: 'workshops#show', as: :authenticated_root
  end

  devise_for :users, :controllers => {:registrations => "users/registrations"}
  root :to => "home#index"

  resources :create_workshop
  #get '/workshop/:id/edit' => 'create_workshop#wicked_first', :as => 'edit_workshop'

  # , only: [:show, :update]
  # controller :workshops do
  #   resources :create_workshop, only: :update
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/_footer.html.erb
<script type="text/javascript">

$(document).ready(function() {

  var bDate = new Date($('.beginDate').html()),
      eDate = new Date($('.endDate').html()),
      cDate = new Date(),
      tDays = eDate - bDate,
      timeLeft = cDate - bDate;

  function updateProgress() {

    var diffDays = Math.round((eDate - cDate)/1000/60/60/24);

    if (diffDays < 0) {
      $('#pbar_text').html("Projet terminé !");
      $('#pbar_innertext').css('width', '100%');
    } else if (bDate > cDate) {
      $('#pbar_text').html("Projet non commencé");
    } else if (diffDays == 0) {
      $('#pbar_text').html("Dernier jour !!");
    } else if (diffDays == 1) {
      $('#pbar_text').html(diffDays + " jour restant");
    } else {
      $('#pbar_text').html(diffDays + " jours restants");
    }
  }

  function progress(timeleft, timetotal) {
    var progressBarWidth = timeleft / timetotal * 100;
    $('#pbar_innertext').animate({ width: progressBarWidth+'%' },
                                  timeleft == timetotal ? 0 : 1000, "linear");
  };

  updateProgress();
  progress(timeLeft, tDays);
});

$('.datepicker_begin').pickadate({
  format: "Début !du projet le dd mmm yyyy",
  today: "",
  clear: "Effacer",
  close: "Fermer"
})

$('.datepicker_end').pickadate({
  format: "Le projet finira le dd mmm yyyy",
  today: "",
  clear: "Effacer",
  close: "Fermer"
})

</script>

app/views/layouts/_header.html.erb
  <nav class='header'>
    <a href="/"><img class="logo" src="/assets/logo.png" alt="Logo"></a>

    <!--<ul class="dropdown">
      <li>
        <button type="button" class="btn btn-primary" data-toggle="dropdown">
          <%= @promo %>
          <span class="caret"></span>
        </button>
      </li>
      <li>
        <ul class="dropdown-menu">
          <% @years.each do |year| %>
            <li><%= link_to year, workshops_path(year)%></li>
          <% end %>
        </ul>
      </li>
    </ul>-->

    <ul>
      <% if user_signed_in? %>
        <li><%= link_to "Promotion", promo_path %></li><span>|</span>
        <li><%= link_to "Liens utiles", liens_path %></li><span>|</span>
        <li><%= link_to "Mon profil", edit_user_registration_path %></li><span>|</span>
        <li><%= link_to 'Se déconnecter', destroy_user_session_path, :method => :delete %></li>
        <li class="open_menu"><i class="fa fa-bars fa-2x" aria-hidden="true"></i></li>
      <% else %>
        <li><%= link_to 'S\'inscrire', new_user_registration_path %></li><span>|</span>
        <li><%= link_to 'Se connecter', new_user_session_path %></li>
        <li class="open_menu"><i class="fa fa-bars fa-2x" aria-hidden="true"></i></li>
      <% end %>
    </ul>
  </nav>

  <nav class='nav_mobile'>
    <div class="logo_mobile">
      <i class="fa fa-times-circle-o fa-2x" aria-hidden="true"></i>
    </div>

    <% if user_signed_in? %>
      <h4><i class="fa fa-user" aria-hidden="true"></i> Mon profil</h4>

      <div class="my_profil">
        <%= link_to current_user.firstname, edit_user_registration_path %>
      </div>
      <div class="my_profil">
        <%= link_to 'Se déconnecter', destroy_user_session_path, :method => :delete %>
      </div>

      <h4><i class="fa fa-hashtag" aria-hidden="true"></i> Divers</h4>
      <div class="my_profil">
        <%= link_to 'Promotion', promo_path %>
      </div>
      <div class="my_profil">
        <%= link_to 'Liens utiles', liens_path %>
      </div>
      <h4><i class="fa fa-list" aria-hidden="true"></i> Workshops</h4>
      <% @workshops.each do |workshop| %>
        <div class="each_workshop <% if @workshops.name == workshop.name  %> active <% end %>">
          <%= link_to workshop.name, workshop_path(workshop.to_param) %>
        </div>
      <% end %>
    <% else %>

      <h4><i class="fa fa-user" aria-hidden="true"></i> Rejoins-nous</h4>

      <div class="my_profil">
        <%= link_to 'S\'inscrire', new_user_registration_path %>
      </div>
      <div class="my_profil">
        <%= link_to 'Se connecter', new_user_session_path %>
      </div>
    <% end %>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grouper</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="/assets/tete_logo.png" />

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render('layouts/header') %>
    <main class="margin_top">
      <%= yield %>
    </main>
    <%= render('layouts/footer') %>
  </body>
</html>